# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
apt_packages:
  - libpoppler-cpp-dev
  - libudunits2-dev
  - libgdal-dev
  - libgeos-dev
  - libproj-dev